# Copyright (c) 2024 Files Community
# Licensed under the MIT License. See the LICENSE.

# NOTE: This is going to be superseded by GitHub Actions in the near future.

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: BuildPipelineVariables
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'

jobs:
- job: StoreRelease
  timeoutInMinutes: 120

  steps:

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        . './.github/scripts/Configure-AppxManifest.ps1' `
          -Branch "Store" `
          -PackageManifestPath "$(Build.SourcesDirectory)\src\Files.App (Package)\Package.appxmanifest" `
          -Publisher "CN=53EC4384-7F5B-4CF6-8C23-513FFE9D1AB7" `
          -WorkingDir "$(Build.SourcesDirectory)" `
          -SecretBingMapsKey "??" `
          -SecretSentry "$(sentry.secret)" `
          -SecretGitHubOAuthClientId "$(githubclientid.secret)"
      failOnStderr: true

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: CmdLine@2
    inputs:
      script: 'for /f %%a in ('dir /b /a:d %localappdata%\Microsoft\VisualStudio\17*') do echo UsePreviews=True>%localappdata%\Microsoft\VisualStudio\%%a\sdk.txt'

  # Restore the solution
  - task: MSBuild@1
    inputs:
      platform: 'x64'
      solution: '**/*.sln'
      configuration: 'Store'
      msbuildArguments: '/t:restore /p:PublishReadyToRun=true'
      maximumCpuCount: true

  # Generate msixupload
  - task: MSBuild@1
    inputs:
      solution: '**/*.wapproj'
      platform: 'x64'
      configuration: 'Store'
      msbuildArguments: '/t:build;_GenerateAppxPackage /p:AppxBundlePlatforms="x64|ARM64";AppxPackageDir="$(appxPackageDir)";AppxBundle=Always;UapAppxPackageBuildMode=StoreUpload'
      maximumCpuCount: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\Store\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'Store'
      publishLocation: 'Container'

  - task: store-flight@0
    inputs:
      serviceEndpoint: 'Files'
      appId: '9NGHP3DX8HDX'
      flightName: 'Files - Preview'
      packagePath: '$(appxPackageDir)\**\*.msixupload'
      force: false
      skipPolling: false
      deletePackages: true
      numberOfPackagesToKeep: '5'
      isMandatoryUpdate: true
