<!--  Copyright (c) Files Community. Licensed under the MIT License.  -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(WindowsTargetFramework)</TargetFramework>
		<TargetPlatformMinVersion>$(MinimalWindowsVersion)</TargetPlatformMinVersion>
		<OutputType>WinExe</OutputType>
		<AssemblyName>Files.App2</AssemblyName>
		<RootNamespace>Files.App2</RootNamespace>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release</Configurations>
		<Platforms>x86;x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
		<EnableMsixTooling>true</EnableMsixTooling>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
		<PackageReference Include="Microsoft.WindowsAppSDK" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="app.manifest" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Files.Core\Files.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Assets\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
